version: '3.9'

services:
  web:
    build:
      dockerfile: Dockerfile
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./project:/sisna-app
    ports:
      - 8000:8000
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
    depends_on:
      - db



